// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEKAbWlR9uxWF9yWqUdKJWD8VR0KaSzUw',
    appId: '1:153024751827:web:8352b16a9ed3b324f80c26',
    messagingSenderId: '153024751827',
    projectId: 'smart-band-cf871',
    authDomain: 'smart-band-cf871.firebaseapp.com',
    databaseURL: 'https://smart-band-cf871-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-band-cf871.appspot.com',
    measurementId: 'G-CGMEXEWPD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJZVu5grPqKru3dCDWBsLUw5mv7bUtNKA',
    appId: '1:153024751827:android:8bcca715cfcb0b68f80c26',
    messagingSenderId: '153024751827',
    projectId: 'smart-band-cf871',
    databaseURL: 'https://smart-band-cf871-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-band-cf871.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCODvYMHdzChmy49tOwt_aEOeGVJPncB68',
    appId: '1:153024751827:ios:8565f1998297387bf80c26',
    messagingSenderId: '153024751827',
    projectId: 'smart-band-cf871',
    databaseURL: 'https://smart-band-cf871-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-band-cf871.appspot.com',
    iosClientId: '153024751827-gl5ekkp604emg7oqo3gbokgoctk75bgu.apps.googleusercontent.com',
    iosBundleId: 'th.ac.kmitl.iot.beeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCODvYMHdzChmy49tOwt_aEOeGVJPncB68',
    appId: '1:153024751827:ios:c4cf08f0d66a6a02f80c26',
    messagingSenderId: '153024751827',
    projectId: 'smart-band-cf871',
    databaseURL: 'https://smart-band-cf871-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-band-cf871.appspot.com',
    iosClientId: '153024751827-pj81849npk4a7se283kvmb6v6vj40pob.apps.googleusercontent.com',
    iosBundleId: 'th.ac.kmitl.iot.beeProject.RunnerTests',
  );
}
